# A Rapid Introduction to Molecular Biology
#Given: A DNA string s of length at most 1000 nt.
#Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s
dataset = ' AAGTCGATGACGTGACTCTTTCGCGGTCCAAGGCCTTATCGAGCTTTGGCCAACAGCGCTACCGCGACTGCGTTAAGCCTATAAACTTCCTTTGAATTTATCTACTTAAAAAGTCTAGGACTATATCGAGAAGTACTCTTCCACCGTAGGACGTGTGATCTGATACAATTGTGCCGTACGATGCCGAGTTGCCCACTCTTCTTTAAGATCACCAGCCGCGTTGTAGTGCCGACTATACTGGATTTTAATAGAAACGCAGGTTGACCAACGATTCTACCTTCTCAAAGTAACTGACGACACCAAACAAGAAGTATGTAAATTAAGGCTAACGTACAGTATCGTCATCCTAGTTCGTGGGGCGTCAGGCTAATGAGCCGCCACATGCGGCCACTCAGTATGTGCATATAAGGCGTTCCGCGTACCCTACATAGGGCGTAGTACAGCCACATCGGGGTGTCTACGTTAACACTGCCTGCAGGCGATTTGCCACCATCGGAATCTTTAAGAATCAGATCGCCGGAACCTAATGGGTCTGCAAATATTACATGTGTCGGCCCCCCTCTTTGCTTTGGACTGGGTGAACGAAATAAGGGCTGACTAATATAGCGGGATATCTATATTAGGGCGGCCGATTCAACGGCCCGTAATAAATCCAAGCTCCTGATCCAGTTTCCAGGTACCTAGGGGATAGCCCAACTTCCAGTGGGGGACGTGGTTGGCGCTAGCGTTCGCCATCAACCTTGAGTTTGTCCAGTACCTGACGTTTTCGGGAAACGGTTGCTGTCCACGCGATAGTAATAGTCAGCCCCTAGGTAAGGCTGTTA '

def count_nucleotides(DNA:str):
    counts = {'A':0, 'C':0, 'G':0, 'T':0}
    for char in DNA.upper():
        if char in 'ACGT':
            counts[char] += 1
        else:
            if char != ' ': raise ValueError(f"Invalid nucleotide '{char}'!")
    return counts

print(*list(count_nucleotides(dataset).values()))
